import type {Metadata} from "next";
import {Inter, Lato} from "next/font/google";
import "./globals.css";
import React from "react";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import Steps from "@/components/steps";
import SatisficationSection from "@/components/satisfication-section";
import FloatingDock from "@/components/floating-dock/floating-dock";
import Providers from "@/components/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Providers>
            <Navbar/>
            <FloatingDock/>
            <Steps/>
            {children}
            <SatisficationSection/>
            <Footer/>
        </Providers>
        </body>
        </html>
    );
}
